### 회원가입 요청
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "12345678",
  "name": "김가윤",
  "gender": "F",
  "birthDate": "2000-05-03"
}

### 로그인 요청
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "12345678"
}


### 건강 정보 요청 (로그인 후 받은 JWT 필요)
POST http://localhost:3000/api/health/safe-health-info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0Njc4OTM1MiwiZXhwIjoxNzQ3Mzk0MTUyfQ.kMWhHxQ4AhKMl9LCs0xAizKSxlth-2_EjAiFnssCi24

{
  "sex": "여성",
  "age": 24,
  "height": 160,
  "weight": 53,
  "chronic": "없음",
  "symptoms": "기침, 피로"
}

### 내 정보 조회
GET http://localhost:3000/api/mypage/me
Authorization: Bearer <로그인_토큰>

### 토큰 유효성 검사
GET http://localhost:3000/api/mypage/verify-token
Authorization: Bearer <로그인_토큰>
